### ISSUE TITLE
Missing source map in compiled source

### ISSUE THREAD

**Issue by quanglam2807** [linonetwo/electron-ipc-cat#22]
I got this warning when using `electron-ipc-cat@1.2.9` via npm
```
Failed to parse source map from '/home/runner/work/switchbar/switchbar/node_modules/electron-ipc-cat/src/common.ts' file: Error: ENOENT: no such file or directory, open '/home/runner/work/switchbar/switchbar/node_modules/electron-ipc-cat/src/common.ts'
Failed to parse source map from '/home/runner/work/switchbar/switchbar/node_modules/electron-ipc-cat/src/fixContextIsolation.ts' file: Error: ENOENT: no such file or directory, open '/home/runner/work/switchbar/switchbar/node_modules/electron-ipc-cat/src/fixContextIsolation.ts'
Failed to parse source map from '/home/runner/work/switchbar/switchbar/node_modules/electron-ipc-cat/src/utils.ts' file: Error: ENOENT: no such file or directory, open '/home/runner/work/switchbar/switchbar/node_modules/electron-ipc-cat/src/utils.ts'
```

**Comment by linonetwo** [comment]
Okay, I didn't notice this, I will add it next time I have time develop my TidGi. I'm recently considering building a metaverse game, that supports modding in the browser. So my time are mostly on that project.

**Comment by linonetwo** [comment]
Seems you have a forked updated version, would you like to PR here? I'm recently focus on tiddlywiki plugins like https://github.com/tiddly-gittly/tiddlywiki-calendar so didn't give much attention here...

**Comment by linonetwo** [comment]
Oh, seems you delete some feature to create a lighter version, that is good. I may copy some code here manually?

**Comment by quanglam2807** [comment]
@linonetwo Sorry for the delay! Yes, definitely, you can copy the code here. I mostly forked to fix issues with serializing errors: https://github.com/webcatalog/electron-ipc-cat/commit/f80a95d4aab220ac616391a4ae5d65ed02a61b4b

**Comment by linonetwo** [comment]
I sync fron your repo, and this seem to be fixed? I can see there are .js.map file generated!

I also fix some bug on Observable Function$ , but you are not using this feature anymore.

But my change in v2.0.1 that uses esm can still reduce the bundle size.
